QLNhaTro_API/Models/HoaDonDichVu.cs
namespace QLNhaTro_API.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("HoaDonDichVu")]
    public partial class HoaDonDichVu
    {

        [Key]
        public int IdHoaDon { get; set; }

        public int IdTaiKhoan { get; set; }

        public int IdPhong { get; set; }

        public int IdKhachHang { get; set; }

        public int TienThanhToan { get; set; }

        public bool TrangThaiThanhToan { get; set; }

        public virtual KhachHang KhachHang { get; set; }

        public virtual Phong Phong { get; set; }

        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}

QLNhaTro_API/Controllers/HoaDonDichVusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using QLNhaTro_API.Models;
using SelectPdf;

namespace QLNhaTro_API.Controllers
{
    public class HoaDonDichVusController : BaseController
    {
        private DBQLNhaTro db = new DBQLNhaTro();

        // GET: HoaDonDichVus
        public ActionResult Index()
        {
            var result = db.ChiTietHoaDons.ToList();
            foreach (var item in result)
            {
                int id = item.IdHoaDon;
                int tientong = db.ChiTietHoaDons.Where(p => p.IdHoaDon == id).Select(p => p.ThanhTien).Sum();
                HoaDonDichVu hoadon = db.HoaDonDichVus.SingleOrDefault(h => h.IdHoaDon == id);
                hoadon.TienThanhToan = tientong;
                db.SaveChanges();
            }
            var hoaDonDichVus = db.HoaDonDichVus.Include(h => h.KhachHang).Include(h => h.Phong).Include(h => h.TaiKhoan);
            return View(hoaDonDichVus.ToList());
        }

        // GET: HoaDonDichVus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            List<ChiTietHoaDon> chiTietHoaDon = db.ChiTietHoaDons.Where(u => u.IdHoaDon == id).ToList();
            if (chiTietHoaDon == null)
            {
                return HttpNotFound();
            }
            return View(chiTietHoaDon);
        }



        //// GET: HoaDonDichVus/Create
        //public ActionResult Create()
        //{
        //    ViewBag.IdKhachHang = new SelectList(db.KhachHangs, "IdKhachHang", "HoTen");
        //    ViewBag.IdPhong = new SelectList(db.Phongs, "IdPhong", "TenPhong");
        //    ViewBag.IdTaiKhoan = new SelectList(db.TaiKhoans, "IdTaiKhoan", "HoTen");
        //    return View();
        //}

        //// POST: HoaDonDichVus/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "IdHoaDon,IdDichVu,IdTaiKhoan,IdPhong,IdKhachHang,TienThanhToan,TrangThaiThanhToan")] HoaDonDichVu hoaDonDichVu)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.HoaDonDichVus.Add(hoaDonDichVu);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.IdKhachHang = new SelectList(db.KhachHangs, "IdKhachHang", "HoTen", hoaDonDichVu.IdKhachHang);
        //    ViewBag.IdPhong = new SelectList(db.Phongs, "IdPhong", "TenPhong", hoaDonDichVu.IdPhong);
        //    ViewBag.IdTaiKhoan = new SelectList(db.TaiKhoans, "IdTaiKhoan", "HoTen", hoaDonDichVu.IdTaiKhoan);
        //    return View(hoaDonDichVu);
        //}

        // GET: HoaDonDichVus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDonDichVu hoaDonDichVu = db.HoaDonDichVus.Find(id);
            if (hoaDonDichVu == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdKhachHang = new SelectList(db.KhachHangs, "IdKhachHang", "HoTen", hoaDonDichVu.IdKhachHang);
            ViewBag.IdPhong = new SelectList(db.Phongs, "IdPhong", "TenPhong", hoaDonDichVu.IdPhong);
            ViewBag.IdTaiKhoan = new SelectList(db.TaiKhoans, "IdTaiKhoan", "HoTen", hoaDonDichVu.IdTaiKhoan);
            return View(hoaDonDichVu);
        }

        // POST: HoaDonDichVus/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdHoaDon,IdDichVu,IdTaiKhoan,IdPhong,IdKhachHang,TienThanhToan,TrangThaiThanhToan")] HoaDonDichVu hoaDonDichVu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hoaDonDichVu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdKhachHang = new SelectList(db.KhachHangs, "IdKhachHang", "HoTen", hoaDonDichVu.IdKhachHang);
            ViewBag.IdPhong = new SelectList(db.Phongs, "IdPhong", "TenPhong", hoaDonDichVu.IdPhong);
            ViewBag.IdTaiKhoan = new SelectList(db.TaiKhoans, "IdTaiKhoan", "HoTen", hoaDonDichVu.IdTaiKhoan);
            return View(hoaDonDichVu);
        }

        // GET: HoaDonDichVus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HoaDonDichVu hoaDonDichVu = db.HoaDonDichVus.Find(id);
            if (hoaDonDichVu == null)
            {
                return HttpNotFound();
            }
            return View(hoaDonDichVu);
        }

        // POST: HoaDonDichVus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HoaDonDichVu hoaDonDichVu = db.HoaDonDichVus.Find(id);
            List<ChiTietHoaDon> chiTietHoaDon = db.ChiTietHoaDons.Where(u => u.IdHoaDon == id).ToList();
            foreach (var item in chiTietHoaDon)
            {
                db.ChiTietHoaDons.Remove(item);
            }
            db.HoaDonDichVus.Remove(hoaDonDichVu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Export()
        {
            HtmlToPdf converter = new HtmlToPdf();

            // set converter options
            converter.Options.PdfPageSize = PdfPageSize.A4;
            converter.Options.PdfPageOrientation = PdfPageOrientation.Portrait;
            converter.Options.MarginLeft = 10;
            converter.Options.MarginRight = 10;
            converter.Options.MarginTop = 20;
            converter.Options.MarginBottom = 20;

            var chitiethoadon = db.ChiTietHoaDons.ToList();

            var htmlPdf = base.RenderPartialToString("~/Views/Shared/PartialViewPdf.cshtml", chitiethoadon, ControllerContext);
            // create a new pdf document converting an html string
            PdfDocument doc = converter.ConvertHtmlString(htmlPdf);
            string fileName = string.Format("{0}.pdf", DateTime.Now.ToString("dd-MM-yyyy"));
            string pathFile = string.Format("{0}/{1}", Server.MapPath("~/Content/filePDF/"), fileName);
            doc.Save(pathFile);
            return Json(fileName, JsonRequestBehavior.AllowGet);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLNhaTro_API/Views/HoaDonDichVus/Delete.cshtml
@model QLNhaTro_API.Models.HoaDonDichVu

@{
    ViewBag.Title = "Xoá";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<p style="text-align:right;margin:10px;">
    <a href="@Url.Action("Index","HoaDonDichVus")" class="btn btn-primary">QUAY LẠI</a>
</p>
<div class="container my-3 rounded rounded-3 border border-2" style="width:40%;">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center my-3">XÓA HÓA ĐƠN DỊCH VỤ?</h1>
            <hr />
            <div class="mb-3">
                <h3 class="form-label">Họ và tên khách hàng: @Html.DisplayFor(model => model.KhachHang.HoTen)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">Số phòng: @Html.DisplayFor(model => model.Phong.TenPhong)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">Ngườu thu tiền: @Html.DisplayFor(model => model.TaiKhoan.HoTen)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">Số tiền thanh toán: @Html.DisplayFor(model => model.TienThanhToan)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">Trạng thái thanh toán: @Html.DisplayFor(model => model.TrangThaiThanhToan)</h3>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="mb-2 text-center">
                    <input type="submit" value="XÓA" class="btn btn-success form-control" style="background-color:red" />
                </div>}
        </div>
    </div>
</div>

QLNhaTro_API/Views/HoaDonDichVus/Details.cshtml
@model IEnumerable<QLNhaTro_API.Models.ChiTietHoaDon>
@using System.Globalization
@{
    ViewBag.Title = "Chi Tiết Hoá Đơn";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<p style="text-align:right;margin:20px;">
    <a href="@Url.Action("Index","HoaDonDichVus")" class="btn btn-primary">QUAY LẠI</a>
</p>
<table class="table" id="myTable">
    <thead>
        <tr>
            <th>
                TÊN DỊCH VỤ
            </th>
            <th>
                TÊN NGƯỜI SỬ DỤNG
            </th>
            <th>
                TỪ NGÀY
            </th>
            <th>
                TỚI NGÀY
            </th>
            <th>
                CHỈ SỐ CŨ
            </th>
            <th>
                CHỈ SỐ MỚI
            </th>
            <th>
                THÀNH TIỀN
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DichVu.TenDichVu)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoaDonDichVu.KhachHang.HoTen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TuNgay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ToiNgay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ChiSoCu)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ChiSoMoi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ThanhTien)
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    jQuery(document).ready(function () {
        $('#myTable').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Vietnamese.json"
            }
        });
    });
</script>

QLNhaTro_API/Views/HoaDonDichVus/Edit.cshtml
@model QLNhaTro_API.Models.HoaDonDichVu

@{
    ViewBag.Title = "Sửa";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <p style="text-align:right;margin:10px;">
        <a href="@Url.Action("Index","HoaDonDichVus")" class="btn btn-primary">QUAY LẠI</a>
    </p>
    <div class="container my-3 rounded rounded-3 border border-2" style="width:40%;">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center my-3">SỬA THÔNG TIN HÓA ĐƠN DICH VỤ</h1>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IdHoaDon)
                <div class="mb-3">
                    <h3 class="form-label">Họ và tên người thu</h3>
                    <div class="col-md-12">
                        @Html.DropDownList("IdTaiKhoan", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IdTaiKhoan, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="mb-3">
                    <h3 class="form-label">Số phòng</h3>
                    <div class="col-md-12">
                        @Html.DropDownList("IdPhong", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IdPhong, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="mb-3">
                    <h3 class="form-label">Họ và tên khách hàng</h3>
                    <div class="col-md-12">
                        @Html.DropDownList("IdKhachHang", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IdKhachHang, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="mb-3">
                    <h3 class="form-label">Số tiền thanh toán</h3>
                    <div class="col-md-12">
                        <p style="font-size: larger"><b> @Html.DisplayFor(model => model.TienThanhToan) VND</b></p>
                    </div>
                </div>
                <div class="mb-3">
                    <h3 class="form-label">Trạng thái thanh toán</h3>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.TrangThaiThanhToan, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TrangThaiThanhToan, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="mb-2 text-center">
                    <input type="submit" value="LƯU" class="btn btn-success form-control" />
                </div>
            </div>
        </div>
    </div>
}

QLNhaTro_API/Views/HoaDonDichVus/Index.cshtml
@using QLNhaTro_API.Models
@model IEnumerable<HoaDonDichVu>
@using System.Globalization
@{
    ViewBag.Title = "Hoá Đơn Dịch Vụ";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<br />

<table class="table" id="myTable">
    <thead>
        <tr>
            <th>
                KHÁCH HÀNG
            </th>
            <th>
                PHÒNG THUÊ
            </th>
            <th>
                NGƯỜI THU TIỀN
            </th>
            <th>
                TIỀN THANH TOÁN
            </th>
            <th>
                TRẠNG THÁI THANH TOÁN
            </th>
            <th>Thao tác</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KhachHang.HoTen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phong.TenPhong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TaiKhoan.HoTen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TienThanhToan)
                </td>
                <td>
                    @if (item.TrangThaiThanhToan == true)
                    {<i class="fas fa-check-circle text-success"></i><b><span style="color:green; padding: 5px">ĐÃ THANH TOÁN</span></b>}
                    else
                    {<i class="fas fa-times-circle text-danger"></i><b><span style="color:red; padding: 5px">CHƯA THANH TOÁN</span></b>}
                </td>
                <td>
                    <a data-toggle="tooltip" data-placement="bottom" title="Sửa" class="btn btn-sm btn-success" href="@Url.Action("Edit","HoaDonDichVus",new { @id = item.IdHoaDon })">
                        <i class="fas fa-edit"></i>
                    </a>
                    <a data-toggle="tooltip" data-placement="bottom" title="Xoá" class="btn btn-sm btn-danger" href="@Url.Action("Delete","HoaDonDichVus",new { @id = item.IdHoaDon })">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                    <a data-toggle="tooltip" data-placement="bottom" title="Xem chi tiết" class="btn btn-sm btn-info" href="@Url.Action("Details","HoaDonDichVus",new { @id = item.IdHoaDon })">
                        <i class="fas fa-info-circle"></i>
                    </a>
                    <a id="btnExport" data-toggle="tooltip" data-placement="bottom" title="Xuất hoá đơn" class="btn btn-sm btn-warning" href="@Url.Action("Export","HoaDonDichVus",new { @id = item.IdHoaDon })">
                        <i class="fas fa-download"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    jQuery(document).ready(function () {
        $('#myTable').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Vietnamese.json"
            }
        });
    });
</script>

<script>
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();

        $('#btnExport').on('click', function () {
            $.get("/HoaDonDichVus/Export", function (resp) {
                window.location.href = "/Content/filePDF/" + resp;
            });
        });  
    });
</script>