QLNhaTro_API/Models/ThuePhong.cs
namespace QLNhaTro_API.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ThuePhong")]
    public partial class ThuePhong
    {
        [Key]
        public int IdThue { get; set; }

        [Required]
        public int IdKhachHang { get; set; }

        public int IdPhong { get; set; }

        [Required(ErrorMessage = "Tiền đặt cọc không được để trống ")]
        public int TienDatCoc { get; set; }

        [Required(ErrorMessage =  "Ngày bắt đầu không được để trống ")]
        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime NgayBatDau { get; set; }

        [Required(ErrorMessage = "Ngày kết thúc không được để trống ")]
        [Column(TypeName = "date")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime NgayKetThuc { get; set; }

        [StringLength(255)]
        public string FileHopDong { get; set; }

        public virtual KhachHang KhachHang { get; set; }

        public virtual Phong Phong { get; set; }
    }
}

QLNhaTro_API/Controllers/ThuePhongsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLNhaTro_API.Helper;
using QLNhaTro_API.Models;

namespace QLNhaTro_API.Controllers
{
    public class ThuePhongsController : BaseController
    {
        private DBQLNhaTro db = new DBQLNhaTro();

        // GET: ThuePhongs
        public ActionResult Index()
        {
            var thuePhongs = db.ThuePhongs.Include(t => t.KhachHang).Include(t => t.Phong);
            return View(thuePhongs.ToList());
        }

        // GET: ThuePhongs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThuePhong thuePhong = db.ThuePhongs.Find(id);
            if (thuePhong == null)
            {
                return HttpNotFound();
            }
            return View(thuePhong);
        }

        // GET: ThuePhongs/Create
        public ActionResult Create()
        {
            List<KhachHang> list = db.KhachHangs.ToList();
            var listtp = db.ThuePhongs.ToList();
            for (int i = 0; i< list.Count; i++)
            {
                for (int j = 0; j< listtp.Count; j++)
                {
                    if (list[i].IdKhachHang == listtp[j].IdKhachHang)
                    {
                        list.Remove(list[i]);
                    }
                }
            }
            ViewBag.IdKhachHang = new SelectList(list, "IdKhachHang", "HoTen");
            ViewBag.IdPhong = new SelectList(db.Phongs.Where(p => p.TrangThai == 0).ToList(), "IdPhong", "TenPhong");
            return View();
        }

        // POST: ThuePhongs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdThue,IdKhachHang,IdPhong,TienDatCoc,NgayBatDau,NgayKetThuc")] ThuePhong thuePhong, HttpPostedFileBase fileUpload)
        {
            ViewBag.IdKhachHang = new SelectList(db.KhachHangs, "IdKhachHang", "HoTen", thuePhong.IdKhachHang);
            ViewBag.IdPhong = new SelectList(db.Phongs, "IdPhong", "TenPhong", thuePhong.IdPhong);
            if (ModelState.IsValid)
            {
                Phong phong = db.Phongs.Find(thuePhong.IdPhong);
                if (phong.IdPhong == thuePhong.IdPhong)
                {
                    phong.TrangThai = 1;
                }
               
                db.ThuePhongs.Add(thuePhong);
                if (fileUpload == null)
                {
                    ViewBag.Error = "Không được để trống file hợp đồng";
                    return View(thuePhong);
                }
                else
                {
                    var extension = Path.GetExtension(fileUpload.FileName);
                    //if (!fileUpload.ContentType.Contains("application"))
                    if (extension != ".docx" && extension != ".doc" && extension != ".pdf")
                    {
                        ViewBag.Error1 = "File hợp đồng không hợp lệ";
                        return View(thuePhong);
                        throw new Exception("File hợp đồng không hợp lệ");
                    }
                    string khachang = db.KhachHangs.Find(thuePhong.IdKhachHang).HoTen;
                    string fileName = Path.GetFileName(RemoveVietnamese.convertToSlug(khachang) + "-fileHopDong" + extension);
                    thuePhong.FileHopDong = "/Content/fileHopDong/" + fileName;
                    fileUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/fileHopDong/"), fileName));
                }
                AddInvoice(thuePhong.IdPhong, thuePhong.IdKhachHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(thuePhong);
        }

        // GET: ThuePhongs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThuePhong thuePhong = db.ThuePhongs.Find(id);
            if (thuePhong == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdKhachHang = new SelectList(db.KhachHangs, "IdKhachHang", "HoTen", thuePhong.IdKhachHang);
            ViewBag.IdPhong = new SelectList(db.Phongs, "IdPhong", "TenPhong", thuePhong.IdPhong);
            return View(thuePhong);
        }

        // POST: ThuePhongs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdThue,IdKhachHang,IdPhong,TienDatCoc,NgayBatDau,NgayKetThuc")] ThuePhong thuePhong, HttpPostedFileBase fileUpload)
        {
            KhachHang khachHang = db.KhachHangs.SingleOrDefault(t => t.IdKhachHang == thuePhong.IdKhachHang);
            var pathold = Path.Combine(Server.MapPath("~/Content/fileHopDong/"), Path.GetFileName(RemoveVietnamese.convertToSlug(khachHang.HoTen) + "-fileHopDong.docx"));
            if (ModelState.IsValid)
            {
                ThuePhong tp = db.ThuePhongs.FirstOrDefault(p => p.IdThue == thuePhong.IdThue);
                tp.TienDatCoc = thuePhong.TienDatCoc;
                tp.NgayBatDau = thuePhong.NgayBatDau;
                tp.NgayKetThuc = thuePhong.NgayKetThuc;
                db.SaveChanges();
                if (fileUpload != null)
                {
                    String FileName = null;
                    var extension = Path.GetExtension(fileUpload.FileName);
                    if (extension != ".docx" && extension != ".doc" && extension != ".pdf")
                    {
                        ViewBag.Error3 = "File hợp đồng không hợp lệ";
                        return View(thuePhong);
                    }
                    FileName = Path.GetFileName(RemoveVietnamese.convertToSlug(khachHang.HoTen) + "-fileHopDong.docx");
                    string _path = Path.Combine(Server.MapPath("~/Content/fileHopDong/"), FileName);
                    try
                    {
                        if (System.IO.File.Exists(pathold)) { System.IO.File.Delete(pathold); }
                        if (System.IO.File.Exists(_path)) { System.IO.File.Delete(_path); }
                    }
                    catch (Exception)
                    { }
                    fileUpload.SaveAs(_path);
                    thuePhong.FileHopDong ="/Content/fileHopDong/" + FileName;
                    var fileold = db.ThuePhongs.Where(x => x.IdThue == thuePhong.IdThue).SingleOrDefault();
                    db.ThuePhongs.Remove(fileold);
                    db.ThuePhongs.Add(thuePhong);
                    db.SaveChanges();
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(thuePhong);
        }

        // GET: ThuePhongs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ThuePhong thuePhong = db.ThuePhongs.Find(id);
            if (thuePhong == null)
            {
                return HttpNotFound();
            }
            return View(thuePhong);
        }

        // POST: ThuePhongs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ThuePhong thuePhong = db.ThuePhongs.Find(id);
            KhachHang khachHang = db.KhachHangs.SingleOrDefault(t => t.IdKhachHang == thuePhong.IdKhachHang);
            HoaDonDichVu hoaDonDichVu = db.HoaDonDichVus.SingleOrDefault(h => h.IdPhong == thuePhong.IdPhong);
            var pathold = Path.Combine(Server.MapPath("~/Content/fileHopDong/"), Path.GetFileName(RemoveVietnamese.convertToSlug(khachHang.HoTen) + "-fileHopDong.docx"));
            Phong phong = db.Phongs.Find(thuePhong.IdPhong);
            if (phong.IdPhong == thuePhong.IdPhong)
            {
                phong.TrangThai = 0;
            }
            try
            {
                if (System.IO.File.Exists(pathold)) System.IO.File.Delete(pathold);
            }
            catch (Exception){ }
            if (hoaDonDichVu == null)
            {
                db.ThuePhongs.Remove(thuePhong);
            }
            else
            {
                DeleteInvoice(thuePhong.IdPhong);
                db.ThuePhongs.Remove(thuePhong);

            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //Hàm thêm hoá đơn
        public void AddInvoice(int idphong, int idkhachhang)
        {
            var hoadon = new HoaDonDichVu();
            //var user = new TaiKhoan();
            hoadon.IdTaiKhoan  = int.Parse(Session["UserAdmin"].ToString());
            hoadon.IdKhachHang = idkhachhang;
            hoadon.IdPhong = idphong;
            hoadon.TienThanhToan = 0;
            hoadon.TrangThaiThanhToan = false;
            db.HoaDonDichVus.Add(hoadon);
        }

        public void DeleteInvoice(int id)
        {
            HoaDonDichVu hoaDonDichVu = db.HoaDonDichVus.SingleOrDefault(p => p.IdPhong == id);
            List<ChiTietHoaDon> chiTietHoaDon = db.ChiTietHoaDons.Where(u => u.IdHoaDon == hoaDonDichVu.IdHoaDon).ToList();
            if (chiTietHoaDon == null)
            {
                db.HoaDonDichVus.Remove(hoaDonDichVu);
            }
            else
            {
                foreach (var item in chiTietHoaDon)
                {
                    db.ChiTietHoaDons.Remove(item);
                }
                db.HoaDonDichVus.Remove(hoaDonDichVu);
            }

QLNhaTro_API/Views/ThuePhongs/Create.cshtml
@model QLNhaTro_API.Models.ThuePhong

@{
    ViewBag.Title = "Thêm";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm("Create", "ThuePhongs", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <p style="text-align:right;margin:10px;">
        <a href="@Url.Action("Index","ThuePhongs")" class="btn btn-primary">QUAY LẠI</a>
    </p>
    <div class="container my-3 rounded rounded-3 border border-2" style="width:40%;">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center my-3">TẠO HỢP ĐỒNG</h1>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <h3 class="form-label">Khách Hàng</h3>
                    <div class="col-md-12">
                        @Html.DropDownList("IdKhachHang", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IdKhachHang, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <h3 class="form-label"> Thuê Phòng</h3>
                    <div class="col-md-12">
                        @Html.DropDownList("IdPhong", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.IdPhong, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <h3 class="form-label">Tiền Đặt Cọc</h3>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.TienDatCoc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TienDatCoc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <h3 class="form-label">Ngày Bắt Đầu</h3>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.NgayBatDau, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                        @Html.ValidationMessageFor(model => model.NgayBatDau, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <h3 class="form-label">Ngày Kết Thúc</h3>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control", type = "date" } })
                        @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
                    </div>
                </div>
                @if (ViewBag.Error1 != null)
                {
                    <div class="alert alert-danger" role="alert">
                        @ViewBag.Error1
                    </div>
                }
                @if (ViewBag.Error != null)
                {
                    <div class="alert alert-danger" role="alert">
                        @ViewBag.Error
                    </div>
                }
                <div class="form-group">
                    <h3 class="form-label">File Mềm Hợp Đồng</h3>
                    <div class="col-md-12">
                        <input title="Thêm file" type="file" name="fileUpload" id="fileUpload" onchange="loadFile(event)" />
                    </div>
                </div>

                <div class="mb-2 text-center">
                    <input type="submit" value="TẠO" class="btn btn-success form-control" />
                </div>
            </div>
        </div>
    </div>
}

QLNhaTro_API/Views/ThuePhongs/Delete.cshtml
@model QLNhaTro_API.Models.ThuePhong

@{
    ViewBag.Title = "Xoá";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<p style="text-align:right;margin:10px;">
    <a href="@Url.Action("Index","ThuePhongs")" class="btn btn-primary">QUAY LẠI</a>
</p>
<div class="container my-3 rounded rounded-3 border border-2" style="width:40%;">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center my-3">XÓA HỢP ĐỒNG</h1>
            <hr />
            <div class="mb-3">
                <h3 class="form-label">Họ và tên khách hàng: @Html.DisplayFor(model => model.KhachHang.HoTen)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">Phòng số: @Html.DisplayFor(model => model.Phong.TenPhong)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">Số tiền đặt cọc: @Html.DisplayFor(model => model.TienDatCoc)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">Ngày nhận phòng: @Html.DisplayFor(model => model.NgayBatDau)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">Ngày trả phòng: @Html.DisplayFor(model => model.NgayKetThuc)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">File hợp đồng: <a href="@Model.FileHopDong" download>@Model.FileHopDong.Replace("/Content/fileHopDong/", "")</a></h3>
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="mb-2 text-center">
                    <input type="submit" value="XÓA" class="btn btn-success form-control" style="background-color:red" />
                </div>}
        </div>
    </div>
</div>

QLNhaTro_API/Views/ThuePhongs/Details.cshtml
@model QLNhaTro_API.Models.ThuePhong

@{
    ViewBag.Title = "Chi Tiết";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<p style="text-align:right;margin:10px;">
    <a href="@Url.Action("Index","ThuePhongs")" class="btn btn-primary">QUAY LẠI</a>
</p>
<div class="container my-3 rounded rounded-3 border border-2" style="width:40%;">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center my-3">THÔNG TIN HỢP ĐỒNG</h1>
            <hr />
            <div class="mb-3">
                <h3 class="form-label">Họ và tên khách hàng: @Html.DisplayFor(model => model.KhachHang.HoTen)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">Phòng số: @Html.DisplayFor(model => model.Phong.TenPhong)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">Số tiền đặt cọc: @Html.DisplayFor(model => model.TienDatCoc)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">Ngày nhận phòng: @Html.DisplayFor(model => model.NgayBatDau)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">Ngày trả phòng: @Html.DisplayFor(model => model.NgayKetThuc)</h3>
            </div>
            <div class="mb-3">
                <h3 class="form-label">File hợp đồng: <a href="@Model.FileHopDong" download>@Model.FileHopDong.Replace("/Content/fileHopDong/", "")</a></h3>
            </div>
        </div>
    </div>
</div>

QLNhaTro_API/Views/ThuePhongs/Edit.cshtml
@model QLNhaTro_API.Models.ThuePhong

@{
    ViewBag.Title = "Sửa";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<p style="text-align:right;margin:10px;">
    <a href="@Url.Action("Index","ThuePhongs")" class="btn btn-primary">QUAY LẠI</a>
</p>

@using (Html.BeginForm("Edit", "ThuePhongs", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container my-3 rounded rounded-3 border border-2" style="width:40%;">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-center my-3">SỬA THÔNG TIN HỢP ĐỒNG</h1>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IdThue)

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IdKhachHang)

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IdPhong)

                <div class="mb-3">
                    <h3 class="form-label">Tiền đặt cọc</h3>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.TienDatCoc, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TienDatCoc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="mb-3">
                    <h3 class="form-label">Ngày bắt đầu</h3>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.NgayBatDau, new { htmlAttributes = new { @class = "form-control", type = "date", value = @Model.NgayBatDau.ToString("yyyy-MM-dd") } })
                        @Html.ValidationMessageFor(model => model.NgayBatDau, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="mb-3">
                    <h3 class="form-label">Ngày kết thúc</h3>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.NgayKetThuc, new { htmlAttributes = new { @class = "form-control", type = "date", value = @Model.NgayKetThuc.ToString("yyyy-MM-dd") } })
                        @Html.ValidationMessageFor(model => model.NgayKetThuc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @if (ViewBag.Error3 != null)
                    {
                        <div class="alert alert-danger" role="alert">
                            @ViewBag.Error3
                        </div>
                    }
                    <div class="mb-3">
                        <h3 class="form-label">File hợp đồng</h3>
                        <div class="col-md-12">
                            <input title="Thêm file" type="file" name="fileUpload" id="fileUpload" onchange="loadFile(event)" />
                        </div>
                    </div>
                </div>
                <div class="mb-2 text-center">
                    <input type="submit" value="Lưu" class="btn btn-success form-control" />
                </div>

            </div>
        </div>
    </div>
}

QLNhaTro_API/Views/ThuePhongs/Index.cshtml
@model IEnumerable<QLNhaTro_API.Models.ThuePhong>

@{
    ViewBag.Title = "Hợp Đồng";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<p style="text-align:right;margin:20px;">
    <a href="@Url.Action("Create","ThuePhongs")" class="btn btn-primary">Tạo mới</a>
</p>
<table class="table" id="myTable">
    <thead>
        <tr>
            <th>
                TÊN NGƯỜI THUÊ
            </th>
            <th>
                PHÒNG THUÊ
            </th>
            <th>
                TIỀN ĐẶT CỌC
            </th>
            <th>
                NGÀY BẮT ĐẦU
            </th>
            <th>
                NGÀY KẾT THÚC
            </th>
            <th>
                HỢP ĐỒNG
            </th>
            <th>Thao tác</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KhachHang.HoTen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phong.TenPhong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TienDatCoc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayBatDau)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NgayKetThuc)
                </td>


                <td>
                    <a href="@item.FileHopDong" download><b>@item.FileHopDong.Replace("/Content/fileHopDong/", "")</b></a>
                </td>
                <td>
                    <a data-toggle="tooltip" data-placement="bottom" title="Sửa" class="btn btn-sm btn-success" href="@Url.Action("Edit","ThuePhongs",new { @id = item.IdThue })">
                        <i class="fas fa-edit"></i>
                    </a>
                    <a data-toggle="tooltip" data-placement="bottom" title="Xoá" class="btn btn-sm btn-danger" href="@Url.Action("Delete","ThuePhongs",new { @id = item.IdThue })">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                    <a data-toggle="tooltip" data-placement="bottom" title="Xem chi tiết" class="btn btn-sm btn-info" href="@Url.Action("Details","ThuePhongs",new { @id = item.IdThue })">
                        <i class="fas fa-info-circle"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    jQuery(document).ready(function () {
        $('#myTable').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.22/i18n/Vietnamese.json"
            }
        });
    });
</script>