QLNhaTro_API/Controllers/DichVusController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using QLNhaTro_API.Models;

namespace QLNhaTro_API.Controllers
{
    public class DichVusController : BaseController
    {
        private DBQLNhaTro db = new DBQLNhaTro();

        // GET: DichVus
        public ActionResult Index()
        {
            return View(db.DichVus.ToList());
        }

        // GET: DichVus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DichVu dichVu = db.DichVus.Find(id);
            if (dichVu == null)
            {
                return HttpNotFound();
            }
            return View(dichVu);
        }

        // GET: DichVus/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DichVus/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdDichVu,TenDichVu,DonGia")] DichVu dichVu)
        {
            if (ModelState.IsValid)
            {
                db.DichVus.Add(dichVu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dichVu);
        }

        // GET: DichVus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DichVu dichVu = db.DichVus.Find(id);
            if (dichVu == null)
            {
                return HttpNotFound();
            }
            return View(dichVu);
        }

        // POST: DichVus/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdDichVu,TenDichVu,DonGia")] DichVu dichVu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dichVu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dichVu);
        }

        // GET: DichVus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DichVu dichVu = db.DichVus.Find(id);
            if (dichVu == null)
            {
                return HttpNotFound();
            }
            return View(dichVu);
        }

        // POST: DichVus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DichVu dichVu = db.DichVus.Find(id);
            db.DichVus.Remove(dichVu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLNhaTro_API/Controllers/KhachHangsController.cs
using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLNhaTro_API.Helper;
using QLNhaTro_API.Models;


namespace QLNhaTro_API.Controllers
{
    public class KhachHangsController : BaseController
    {
        private DBQLNhaTro db = new DBQLNhaTro();

        // GET: KhachHangs
        public ActionResult Index()
        {
            return View(db.KhachHangs.ToList());
        }
        public ActionResult TestFectchAPI()
        {
            return View();
        }

        // GET: KhachHangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // GET: KhachHangs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KhachHangs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdKhachHang,HoTen,Sdt,GioiTinh,QueQuan,HKTT,SoCMND")] KhachHang khachHang, HttpPostedFileBase fileUpload)
        {
            if (ModelState.IsValid)
            { 
                if (fileUpload == null)
                {
                    ViewBag.Error = "Không được để trống file hình ảnh";
                    return View(khachHang);
                }
                else
                {
                    if (!fileUpload.ContentType.Contains("image"))
                    {
                        ViewBag.Error2 = "File hình không hợp lệ";
                        return View(khachHang);
                        throw new Exception("File hình không hợp lệ");
                    }
                    string extension = Path.GetExtension(fileUpload.FileName);
                    if (fileUpload.ContentLength > 3 * 1024 * 1024) throw new Exception("Hình ảnh vượt quá 3Mb");
                    String _FileName = null;
                    _FileName = Path.GetFileName(RemoveVietnamese.convertToSlug(khachHang.HoTen.ToLower()) + "-anhCMND" + extension);
                    string _path = Path.Combine(Server.MapPath("~/Content/imgCMND/"), _FileName);
                    fileUpload.SaveAs(_path);
                    khachHang.SoCMND ="/Content/imgCMND/" + _FileName;
                    db.KhachHangs.Add(khachHang);
                    db.SaveChanges();

                }
                return RedirectToAction("Index");
            }
            return View(khachHang);
        }
        // GET: KhachHangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: KhachHangs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdKhachHang,HoTen,Sdt,GioiTinh,QueQuan,HKTT,SoCMND")] KhachHang khachHang, HttpPostedFileBase fileUpload)
        {
            var pathold = Path.Combine(Server.MapPath("~/Content/imgCMND/"), Path.GetFileName(RemoveVietnamese.convertToSlug(khachHang.HoTen.ToLower()) + "-anhCMND.png"));
            if (ModelState.IsValid)
            {
                ThuePhong thuephong = db.ThuePhongs.SingleOrDefault(p => p.IdKhachHang == khachHang.IdKhachHang);
                if (thuephong != null)
                {
                    ViewBag.Error2 = "Khách hàng đã tạo hợp đồng. Vui lòng không thay đổi thông tin";
                    return View(khachHang);
                }
                KhachHang kh = db.KhachHangs.FirstOrDefault(p => p.IdKhachHang == khachHang.IdKhachHang);
                kh.HoTen = khachHang.HoTen;
                kh.Sdt = khachHang.Sdt;
                kh.GioiTinh = khachHang.GioiTinh;
                kh.QueQuan = khachHang.QueQuan;
                kh.HKTT = khachHang.HKTT;
                db.SaveChanges();
                if (fileUpload != null)
                {
                    if (!fileUpload.ContentType.Contains("image"))
                    {
                        ViewBag.Error1 = "File hình không hợp lệ";
                        return View(khachHang);
                        throw new Exception("File hình không hợp lệ");
                    }
                    if (fileUpload.ContentLength > 3 * 1024 * 1024) throw new Exception("Hình ảnh vượt quá 3Mb");
                    String _FileName = null;
                    _FileName = Path.GetFileName(RemoveVietnamese.convertToSlug(khachHang.HoTen.ToLower()) + "-anhCMND.png");
                    string _path = Path.Combine(Server.MapPath("~/Content/imgCMND/"), _FileName);
                    try
                    {
                        if (System.IO.File.Exists(pathold)) System.IO.File.Delete(pathold);
                        if (System.IO.File.Exists(_path)) System.IO.File.Delete(_path);
                    }
                    catch (Exception)
                    { }
                    fileUpload.SaveAs(_path);
                    khachHang.SoCMND ="/Content/imgCMND/" + _FileName;
                    var imgold = db.KhachHangs.Where(x => x.IdKhachHang == khachHang.IdKhachHang).SingleOrDefault();
                    db.KhachHangs.Remove(imgold);
                    db.KhachHangs.Add(khachHang);
                    db.SaveChanges();
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(khachHang);
        }

        // GET: KhachHangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KhachHang khachHang = db.KhachHangs.Find(id);
            if (khachHang == null)
            {
                return HttpNotFound();
            }
            return View(khachHang);
        }

        // POST: KhachHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KhachHang khachHang = db.KhachHangs.Find(id);
            var pathold = Path.Combine(Server.MapPath("~/Content/imgCMND/"), Path.GetFileName(RemoveVietnamese.convertToSlug(khachHang.HoTen.ToLower()) + "-anhCMND.png"));
            ThuePhong thuephong = db.ThuePhongs.SingleOrDefault(p => p.IdKhachHang == id);
            if (thuephong != null)
            {
                ViewBag.Error3 = "Khách hàng đã tạo hợp đồng. Nếu muốn xoá hãy thực hiện xoá hợp đồng trước. Cảm ơn";
                return View(khachHang);
            }
            try
            {
                if (System.IO.File.Exists(pathold)) System.IO.File.Delete(pathold);
            }
            catch (Exception){ }
            db.KhachHangs.Remove(khachHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLNhaTro_API/Controllers/PhongsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using QLNhaTro_API.Models;

namespace QLNhaTro_API.Controllers
{
    public class PhongsController : BaseController
    {
        private DBQLNhaTro db = new DBQLNhaTro();

        // GET: Phongs
        public ActionResult Index()
        {
            return View(db.Phongs.ToList());
        }
        // GET: Phongs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Phongs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPhong,TenPhong,TrangThai")] Phong phong)
        {
            if (ModelState.IsValid)
            {
                phong.TrangThai = 0;
                db.Phongs.Add(phong);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(phong);
        }

        // GET: Phongs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phong phong = db.Phongs.Find(id);
            if (phong == null)
            {
                return HttpNotFound();
            }
            return View(phong);
        }

        // POST: Phongs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPhong,TenPhong,TrangThai")] Phong phong, FormCollection formCollection)
        {
            int bien = int.Parse(formCollection["TrangThai"].ToString());
            if (ModelState.IsValid)
            {
                phong.TrangThai = bien;
                db.Entry(phong).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(phong);
        }

        // GET: Phongs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phong phong = db.Phongs.Find(id);
            if (phong == null)
            {
                return HttpNotFound();
            }
            return View(phong);
        }

        // POST: Phongs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Phong phong = db.Phongs.Find(id);
            if(phong.TrangThai == 1)
            {
                ViewBag.Error = "Phòng đã được thuê !";
                return View(phong);
            }
            db.Phongs.Remove(phong);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLNhaTro_API/Controllers/TaiKhoansController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using QLNhaTro_API.Helper;
using QLNhaTro_API.Models;

namespace QLNhaTro_API.Controllers
{
    public class TaiKhoansController : BaseController
    {
        private DBQLNhaTro db = new DBQLNhaTro();

        // GET: TaiKhoans
        public ActionResult Index()
        {
            return View(db.TaiKhoans.ToList());
        }

        // GET: TaiKhoans/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // GET: TaiKhoans/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TaiKhoans/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdTaiKhoan,HoTen,Sdt,DiaChi,Username,Password")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                taiKhoan.Password = MD5Helper.MD5Hash(taiKhoan.Password);
                db.TaiKhoans.Add(taiKhoan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(taiKhoan);
        }

        // GET: TaiKhoans/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: TaiKhoans/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdTaiKhoan,HoTen,Sdt,DiaChi,Username,Password")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taiKhoan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(taiKhoan);
        }

        // GET: TaiKhoans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        // POST: TaiKhoans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            db.TaiKhoans.Remove(taiKhoan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLNhaTro_API/Views/Shared/PartialViewPdf.cshtml
@model List<QLNhaTro_API.Models.ChiTietHoaDon>

<div id="all" style="padding-left: 40px;">
    <div id="content">
        <div id="hot">
            <div class="box py-1">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h2 style="text-align: center; width: max-content; ">CỘNG HOÀ XÃ HỘI CHỦ NGHĨA VIỆT NAM</h2>
                            <h3 style="text-align: center; width: max-content; text-decoration: underline; padding-bottom:10px;">Độc lập - Tự do - Hạnh phúc</h3>
                            <h1 style="text-align: center; width: max-content; margin-top:50px;"><b>HOÁ ĐƠN SỬ DỤNG DỊCH VỤ</b></h1>

                            <h3 style="margin-top: 50px; padding-left: 50px; width: max-content;"><b>Tên khách hàng :</b>@Model.First().HoaDonDichVu.KhachHang.HoTen</h3>
                            <h3 style="padding-left: 50px; width: max-content; "><b>Tên phòng :</b> @Model.First().HoaDonDichVu.Phong.TenPhong</h3>
                            <h3 style="padding-left: 50px; width: max-content; "><b>Người thu tiền :</b> @Model.First().HoaDonDichVu.TaiKhoan.HoTen</h3>
                            <div class="section-border"></div>
                        </div>
                    </div>
                </div>
            </div>
            <table class="table table-bordered" style="width: max-content; margin: 0 auto; padding: 5px; border: 1px solid #808080;" border="1">
                <thead style="width:max-content; padding:5px;">
                    <tr>
                        <th style="width: max-content; padding: 10px;">TÊN DỊCH VỤ</th>
                        <th style="width: max-content; padding: 10px;">TÊN NGƯỜI SỬ DỤNG</th>
                        <th style="width: max-content; padding: 10px;">TỪ NGÀY</th>
                        <th style="width: max-content; padding: 10px;">TỚI NGÀY</th>
                        <th style="width: max-content; padding: 10px;">CHỈ SỐ CŨ </th>
                        <th style="width: max-content; padding: 10px;">CHỈ SỐ MỚI</th>
                        <th style="width: max-content; padding: 10px;">THÀNH TIỀN</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="width: max-content; padding: 10px;">
                                @Html.DisplayFor(modelItem => item.DichVu.TenDichVu)
                            </td>
                            <td style="width: max-content; padding: 10px;">
                                @Html.DisplayFor(modelItem => item.HoaDonDichVu.KhachHang.HoTen)
                            </td>

                            <td style="width: max-content; padding: 10px;">
                                @Convert.ToDateTime(item.TuNgay).ToString("dd/MM/yyyy")
                            </td>
                            <td style="width: max-content; padding: 10px;">
                                @Convert.ToDateTime(item.ToiNgay).ToString("dd/MM/yyyy")
                            </td>
                            <td style="width: max-content; padding: 10px;">
                                @Html.DisplayFor(modelItem => item.ChiSoCu)
                            </td>
                            <td style="width: max-content; padding: 10px;">
                                @Html.DisplayFor(modelItem => item.ChiSoMoi)
                            </td>
                            <td style="width:max-content; padding:10px;">
                                @Html.DisplayFor(modelItem => item.ThanhTien)
                            </td>
                        </tr>

                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="7" style="text-align: right; ">
                            <b>Tổng tiền : @Model.First().HoaDonDichVu.TienThanhToan đ</b>
                        </td>
                    </tr>
                </tfoot>
            </table>
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                    </div>
                    <div class="col-md-6" style="text-align: right; padding: 40px;">
                        <h3>   TP.HCM, ngày @DateTime.Now.ToString("dd") Tháng @DateTime.Now.ToString("MM") Năm @DateTime.Now.ToString("yyyy")</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

QLNhaTro_API/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="shortcut icon" href="~/Content/Image/logologin.png">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="/Content/vendor/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Fontastic Custom icon font-->
    <link rel="stylesheet" href="/Content/css/fontastic.css">
    <!-- Google fonts - Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <!-- jQuery Circle-->
    <link rel="stylesheet" href="/Content/css/grasp_mobile_progress_circle-1.0.0.min.css">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="/Content/css/style.default.css" id="theme-stylesheet">
    <script src="/Content/vendor/jquery/jquery.min.js"></script>
    <!-- Custom stylesheet - for your changes-->
    <link href="~/Content/css/custom.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>
    <!-- Tweaks for older IEs-->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->

    <title>@ViewBag.Title</title>
    @RenderSection("head", required: false)

</head>
<body>
    <!-- Side Navbar -->
    <nav class="side-navbar">
        <div class="side-navbar-wrapper">
            <!-- Sidebar Header    -->
            <div class="sidenav-header d-flex align-items-center justify-content-center">
                <!-- User Info-->
                <div class="sidenav-header-inner text-center">

                    <h2 class="h5"> @Session["fullName"]</h2>
                </div>
                <!-- Small Brand information, appears on minimized sidebar-->
                <div class="sidenav-header-logo"><a href="index.html" class="brand-small text-center"> <strong>B</strong><strong class="text-primary">D</strong></a></div>
            </div>
            <!-- Sidebar Navigation Menus-->
            <div class="main-menu">
                <h5 class="sidenav-heading">Tác Vụ</h5>
                <ul id="side-main-menu" class="side-menu list-unstyled">
                    <li><a href="@Url.Action("Index","Phongs")"> <i class="fas fa-house-user"></i>QUẢN LÝ PHÒNG</a></li>
                    <li><a href="@Url.Action("Index","KhachHangs")"> <i class="far fa-user-circle"></i>QUẢN LÝ KHÁCH HÀNG</a></li>
                    <li><a href="@Url.Action("Index","DichVus")"> <i class="fas fa-concierge-bell"></i>QUẢN LÝ DỊCH VỤ</a></li>
                    <li><a href="@Url.Action("Index","TaiKhoans")"> <i class="fas fa-key"></i>QUẢN LÝ TÀI KHOẢN</a></li>
                    <li><a href="@Url.Action("Index","HoaDonDichVus")"> <i class="fas fa-dollar-sign"></i>HOÁ ĐƠN DỊCH VỤ</a></li>
                    <li><a href="@Url.Action("Index","ThuePhongs")"> <i class="fas fa-clipboard-list"></i>QUẢN LÝ HỢP ĐỒNG</a></li>           
                </ul>
            </div>
            <div class="admin-menu">
                <h5 class="sidenav-heading">Thông tin</h5>
                <ul id="side-admin-menu" class="side-menu list-unstyled">
                    <li> <a href="@Url.Action("Logout","Auth")"> <i class="fas fa-sign-out-alt"></i>Đăng xuất</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="page">
        <header class="header">
            <nav class="navbar">
                <div class="container-fluid">
                    <div class="navbar-holder d-flex align-items-center justify-content-between">
                        <div class="navbar-header">
                            <a id="toggle-btn" href="#" class="menu-btn"><i class="fas fa-bars"></i></a><a href="#" class="navbar-brand">
                                <div class="brand-text d-none d-md-inline-block"><span></span><strong class="text-primary">QUẢN LÝ NHÀ TRỌ</strong></div>
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        @RenderBody()

        <footer class="main-footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-6">
                        <p>Create time &copy; 2021</p>
                    </div>
                    <div class="col-sm-6 text-right">
                        <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions and it helps me to run Bootstrapious. Thank you for understanding :)-->
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <!-- JavaScript files-->
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/js/grasp_mobile_progress_circle-1.0.0.min.js"></script>
    <script src="~/Content/vendor/jquery.cookie/jquery.cookie.js"></script>
    <script src="~/Content/vendor/jquery-validation/jquery.validate.min.js"></script>
    <script src="~/Content/vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
    <!-- Main File-->
    <script src="~/Content/js/front.js"></script>
</body>
</html>